sudo: required

language: java

addons:
  hosts:
    - pcap4j-test
  hostname: pcap4j-test

git:
  quiet: true
  depth: 1

branches:
  only:
    - v1

matrix:
  include:
    - os: linux
      jdk: oraclejdk9
      env: COVERALLS=yes
    - os: linux
      jdk: openjdk11
      addons:
        apt:
          packages:
            - openjdk-6-jdk
    - os: osx
      osx_image: xcode10.1 # OpenJDK 11.0.1+13
      addons:
        homebrew:
          packages:
            - libpcap
  fast_finish: true

cache:
  directories:
    - $HOME/.m2

install:
  - |
    if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      git clone -b libpcap-1.7.4 --depth 1 git://github.com/the-tcpdump-group/libpcap.git libpcap
      cd libpcap
      ./configure
      make && sudo make install
    fi

script:
  - |
    cd "${TRAVIS_BUILD_DIR}"
    if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      if [ "${COVERALLS}" = "yes"  ]; then
        sudo ./mvnw --global-toolchains mvn/toolchains_travis_9.xml -Dorg.pcap4j.core.pcapLibName=/usr/local/lib/libpcap.so -B -DserviceJobId=$TRAVIS_JOB_ID -Dorg.pcap4j.core.test.enableTimestampPrecisionTests=true -P test-coverage verify coveralls:report
      else
        sudo ./mvnw --global-toolchains mvn/toolchains_travis_11.xml -Dorg.pcap4j.core.pcapLibName=/usr/local/lib/libpcap.so -Dorg.pcap4j.jre6-test.jvm=/usr/lib/jvm/java-6-openjdk-amd64/jre/bin/java -B install
      fi
    else
      sudo ./mvnw --global-toolchains mvn/toolchains_travis_mac.xml -B -Djna.library.path="$(find /usr/local/Cellar/libpcap/ -name lib)" install
    fi

notifications:
  email:
    recipients:
      - kaitoy@pcap4j.org
    on_success: change
    on_failure: always
