version: 2.1

executors:
  docker-jdk10:
    docker:
      - image: circleci/openjdk:10.0.2-13-jdk

jobs:
  test:
    executor: docker-jdk10
    steps:
      - checkout
      - run:
          name: Install libpcap
          command: |
            sudo apt-get update
            sudo apt-get install -y libpcap0.8
      - run:
          name: Run mvnw verify
          command: ./mvnw verify --global-toolchains mvn/toolchains_circleci_10.xml

workflows:
  version: 2
  test:
    jobs:
      - test:
          filters:
            branches:
              only: v1
